const mongoose = require("mongoose");

const studlSchema = new mongoose.Schema({
    slno:{
        type:Number,
    },
    admnno:{
        type:String,
    },
    aadharno:{
        type:String,
    },
    classr:{
        type:String,
    },
    stuname:{
        type:String,
    },
    unit:{
        type:String,
    },
    section:{
        type:String,
    },
    rollno:{
        type:Number,
    },
    dob:{
        type:String,
    },
    mothert:{
        type:String,
    },
    caste:{
        type:String,
    },
    religion:{
        type:String,
    },
    flan:{
        type:String,
    },
    sex:{
        type:String,
    },
    bloodgr:{
        type:String,
    },
    transport:{
        type:String,
    },
    fname:{
        type:String,
    },
    fedu:{
        type:String,
    },
    foccu:{
        type:String,
    },
    ftel:{
        type:Number,
    },
    mname:{
        type:String,
    },
    medu:{
        type:String,
    },
    moccu:{
        type:String,
    },
    mtel:{
        type:Number,
    },
    resiprnts:{
        type:String,
    },
    resiphone:{
        type:Number,
    },
    income:{
        type:Number,
    },
    gtel:{
        type:Number,
        default:0
    },
    active:{
        type:String,
        default:"YES"
    },

});


module.exports = mongoose.model("studl", studlSchema);